version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: "rabbitmq"
    ports:
      - "5675:5672"
      - "15675:15672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json